{% set name = "fypp" %}
{% set version = "3.3" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14bb98c370873624c0a5e53bcf30f6ef0e1a3885e0f0cc714774c745ed8543f1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - fypp = fypp:run_fypp

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  source_files:
    - test/
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - fypp
  commands:
    - fypp --help
    - pip check
    - cd test && python -m unittest discover -v

about:
  home: https://github.com/aradi/fypp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python powered Fortran preprocessor'

  description: |
    Fypp is a Python powered preprocessor. It can be used for any
    programming languages but its primary aim is to offer a Fortran
    preprocessor, which helps to extend Fortran with condititional
    compiling and template metaprogramming capabilities.
  doc_url: http://fypp.readthedocs.org/
  dev_url: https://github.com/aradi/fypp

extra:
  recipe-maintainers:
    - aradi
    - jan-janssen
